name: Create Branch on Issue

on:
  issues:
    types: [opened]  # Issue가 생성될 때 트리거됨

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Debug API Response
        env:
          GITHUB_TOKEN: ${{ secrets.DR_RATE_ORGANIZATION_ACCESS_TOKEN }}  # 수정된 부분
        run: |
          # GitHub API를 사용하여 issue의 label 및 title 정보 가져오기
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/BitCamp-Final-Project/Dr.Rate-Backend/issues/${{ github.event.issue.number }})

          # API 응답 데이터 출력
          echo "API Response: $RESPONSE"

          # label 이름과 제목 추출
          LABEL_NAME=$(echo "$RESPONSE" | jq -r '.labels[0].name')
          TITLE=$(echo "$RESPONSE" | jq -r '.title')

          # 추출된 값 출력
          echo "Extracted Label Name: $LABEL_NAME"
          echo "Extracted Title: $TITLE"

          # '[Feat] :' 부분을 제거하고 나머지 텍스트만 추출
          CUSTOM_NAME=$(echo "$TITLE" | sed -E 's/^\[.*\] : //')

          # 브랜치 이름 설정: label/custom-name
          BRANCH_NAME="${LABEL_NAME}/${CUSTOM_NAME}"

          # 브랜치 생성 및 푸시
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"

      - name: Comment on the issue
        run: |
          echo "Branch '$BRANCH_NAME' created for issue #${{ github.event.issue.number }}"
